version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./Adobe.txt:/app/Adobe.txt
      - ./requirements.txt:/app/requirements.txt
    restart: unless-stopped

  frontend:
    build:
      context: ./resume-gui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./resume-gui:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped
